"""Stable scalar ABI shared by the Wasm guest facade and Python host."""

from enum import IntEnum


class Op(IntEnum):
	GET_ROUND_NUM = 1
	GET_COOLDOWN_TURNS = 2
	GET_ENERGY = 3
	GET_DEFENCE = 4
	GET_ID = 5
	GET_LOCATION = 6
	GET_TEAM = 7
	GET_TYPE = 8
	GET_RADIO = 9
	GET_CHARGE_POINT = 10
	GET_ENTITY_COUNT = 11
	IS_READY = 12
	GET_ALL_TEAMS_COUNT = 13
	GET_ALL_TEAMS_AT = 14
	GET_OPPONENT_COUNT = 15
	GET_OPPONENT_AT = 16
	GET_OVERDRIVE_FACTOR = 17
	IS_OPPONENT = 18
	IS_BLOCKED = 19
	IS_LOCATION_OCCUPIED = 20
	ON_THE_MAP = 21
	CAN_DETECT_LOCATION = 22
	CAN_DETECT_RADIUS = 23
	CAN_SENSE_LOCATION = 24
	CAN_SENSE_RADIUS = 25
	SENSE_AETHER = 26
	CAN_CHARGE = 27
	CAN_BUILD = 28
	CAN_OVERDRIVE = 29
	CAN_ANALYZE_ID = 30
	CAN_ANALYZE_LOCATION = 31
	CAN_MOVE = 32
	CAN_SET_RADIO = 33
	CHARGE = 34
	BUILD = 35
	OVERDRIVE = 36
	ANALYZE_ID = 37
	ANALYZE_LOCATION = 38
	MOVE = 39
	SET_RADIO = 40
	SENSE_COUNT = 41
	SENSE_ID = 42
	SENSE_ENERGY = 43
	SENSE_DEFENCE = 44
	SENSE_INIT_DEFENCE = 45
	SENSE_LOCATION = 46
	SENSE_TEAM = 47
	SENSE_TYPE = 48
	SENSE_RADIO = 49
	DETECT_PREPARE = 50
	DETECT_LOCATION = 51
	RANDOM_INT = 52


ERROR_I64 = -(1 << 63)
